# Generated by Django 5.0 on 2024-01-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_orgverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_orgverification',
        ),
    ]
