# Generated by Django 5.0 on 2024-02-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_orgverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scholarshiptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type', models.CharField(max_length=50)),
            ],
        ),
    ]
