# Generated by Django 5.0 on 2024-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_scholarshiptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_comptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(max_length=50)),
            ],
        ),
    ]
