# Generated by Django 5.0 on 2024-01-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_orgverification'),
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_helpreque',
            new_name='tbl_helprequest',
        ),
    ]
