# Generated by Django 5.0 on 2024-01-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_rename_tbl_helpreque_tbl_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_helprequest',
            name='status',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
