# Generated by Django 5.0 on 2024-02-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_medicalshop'),
        ('Helpers', '0005_delete_tbl_helpreque'),
        ('Organization', '0003_tbl_helprequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_address', models.CharField(max_length=50)),
                ('book_contact', models.CharField(max_length=50)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_organization')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpers.tbl_post')),
            ],
        ),
    ]
