# Generated by Django 5.0 on 2024-02-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_tbl_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_book',
        ),
    ]
