# Generated by Django 5.0 on 2024-02-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_tbl_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_book',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
