# Generated by Django 5.0 on 2024-02-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_medicalshop'),
        ('Helpers', '0011_tbl_scholarshipname'),
        ('Organization', '0007_tbl_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scholarshipapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('document', models.FileField(upload_to='MemberDocs/')),
                ('date', models.DateField(auto_now_add=True)),
                ('org_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_organization')),
                ('scholarship_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpers.tbl_scholarshipname')),
            ],
        ),
    ]
