# Generated by Django 5.0 on 2024-02-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0010_tbl_usercomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_usercomplaint',
        ),
    ]
