# Generated by Django 5.0 on 2024-03-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0013_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
