# Generated by Django 5.0 on 2024-03-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0015_tbl_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rating',
            name='org_name',
            field=models.CharField(max_length=50),
        ),
    ]
