# Generated by Django 5.0 on 2024-04-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0017_alter_tbl_rating_rating_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
