# Generated by Django 5.0 on 2024-04-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0019_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
