# Generated by Django 5.0 on 2024-04-11 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_medicalshop'),
        ('Organization', '0021_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacktitle', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('complaintdate', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_organization')),
            ],
        ),
    ]
