# Generated by Django 5.0 on 2024-01-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.FileField(upload_to='Post/')),
                ('post_content', models.CharField(max_length=50)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_request')),
            ],
        ),
    ]
