# Generated by Django 5.0 on 2024-01-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_post',
        ),
    ]
