# Generated by Django 5.0 on 2024-01-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_request'),
        ('Helpers', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_helpreque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_price', models.CharField(max_length=50)),
                ('req_content', models.CharField(max_length=50)),
                ('req_proof', models.FileField(upload_to='Requests/')),
                ('req_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_request')),
            ],
        ),
    ]
