# Generated by Django 5.0 on 2024-01-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0004_tbl_helpreque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_helpreque',
        ),
    ]
