# Generated by Django 5.0 on 2024-02-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0005_delete_tbl_helpreque'),
        ('Organization', '0005_delete_tbl_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_post',
        ),
    ]
