# Generated by Django 5.0 on 2024-02-11 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_delete_tbl_orgverification'),
        ('Guest', '0004_tbl_medicalshop'),
        ('Helpers', '0006_delete_tbl_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.FileField(upload_to='Post/')),
                ('post_content', models.CharField(max_length=50)),
                ('helpers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_helper')),
                ('post_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_request')),
            ],
        ),
    ]
