# Generated by Django 5.0 on 2024-02-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_medicalshop'),
        ('Helpers', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=50)),
                ('ad_image', models.FileField(upload_to='Advertisements/')),
                ('ad_content', models.CharField(max_length=50)),
                ('ad_contact', models.CharField(max_length=50)),
                ('helpers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_helper')),
            ],
        ),
    ]
