# Generated by Django 5.0 on 2024-02-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0008_tbl_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_advertisement',
        ),
    ]
