# Generated by Django 5.0 on 2024-02-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0011_tbl_scholarshipname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_advertisement',
        ),
    ]
