# Generated by Django 5.0 on 2024-01-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_name', models.CharField(max_length=50)),
                ('helper_email', models.CharField(max_length=50)),
                ('helper_contact', models.CharField(max_length=50)),
                ('helper_address', models.CharField(max_length=50)),
                ('helper_photo', models.FileField(upload_to='Helpdoc/')),
                ('helper_password', models.CharField(max_length=50)),
                ('helper_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('helper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
            ],
        ),
    ]
