# Generated by Django 5.0 on 2024-01-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_request'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('org_email', models.CharField(max_length=50)),
                ('org_contact', models.CharField(max_length=50)),
                ('org_address', models.CharField(max_length=50)),
                ('org_logo', models.FileField(upload_to='Orgdoc/')),
                ('org_proof', models.FileField(upload_to='Orgdoc/')),
                ('org_password', models.CharField(max_length=50)),
                ('org_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
            ],
        ),
    ]
